# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendTime', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
                ('pitch', models.CharField(max_length=200)),
                ('tempC', models.CharField(max_length=200)),
                ('leftState', models.CharField(max_length=200)),
                ('rightState', models.CharField(max_length=200)),
            ],
        ),
    ]
