# Generated by Django 2.0 on 2018-02-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roverapp', '0003_datareceived_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareceived',
            name='propellorState',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
    ]
