# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roverapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='DataReceived',
        ),
    ]
