# Generated by Django 2.0 on 2018-02-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roverapp', '0002_auto_20180225_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareceived',
            name='distance',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
